# Generated by Django 5.2.10 on 2026-01-18 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0002_tblrepartidor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblrepartidor',
            name='FechaAServir',
        ),
        migrations.RemoveField(
            model_name='tblrepartidor',
            name='Prioridad',
        ),
    ]
