# Generated by Django 5.2.10 on 2026-01-19 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0003_remove_tblrepartidor_fechaaservir_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblFormulado',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Folio', models.CharField(max_length=15, null=True)),
                ('CantidadSolicitada', models.IntegerField(null=True)),
                ('CantidadServida', models.IntegerField(null=True)),
                ('Fecha', models.DateTimeField(max_length=150, null=True)),
                ('FechaServida', models.DateTimeField(max_length=150, null=True)),
                ('IDEstatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblestatus')),
                ('IDMateriaPrima', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblmateriaprima')),
                ('IDProducto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblproductos')),
                ('IDTolva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tbltolva')),
            ],
        ),
    ]
