# Generated by Django 5.2.10 on 2026-01-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0004_tblformulado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblformulado',
            name='Proporcion',
            field=models.IntegerField(null=True),
        ),
    ]
