# Generated by Django 5.2.10 on 2026-01-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0005_tblformulado_proporcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblformulado',
            name='Proporcion',
            field=models.FloatField(null=True),
        ),
    ]
