# Generated by Django 5.2.10 on 2026-01-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0006_alter_tblformulado_proporcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblformulado',
            name='CantidadServida',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tblformulado',
            name='CantidadSolicitada',
            field=models.FloatField(null=True),
        ),
    ]
