# Generated by Django 5.2.10 on 2026-01-26 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0007_alter_tblformulado_cantidadservida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblCalcularFormulado',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Folio', models.CharField(max_length=15, null=True)),
                ('CantidadBatch', models.FloatField(null=True)),
                ('CantidadRestante', models.FloatField(null=True)),
                ('IDEstatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblestatus')),
                ('IDProducto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblproductos')),
                ('IDTolva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tbltolva')),
            ],
        ),
    ]
