# Generated by Django 5.2.10 on 2026-01-26 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0008_tblcalcularformulado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tblCalcularFormulado',
        ),
    ]
