# Generated by Django 5.2.10 on 2026-01-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0009_delete_tblcalcularformulado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblformulado',
            name='CantidadSolicitada',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
