# Generated by Django 5.2.10 on 2026-02-13 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0010_alter_tblformulado_cantidadsolicitada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Alias', models.CharField(max_length=100)),
                ('Estatus', models.BooleanField(default=True)),
                ('Token', models.CharField(max_length=100)),
                ('Movil', models.BooleanField(default=True)),
                ('ComBau', models.IntegerField()),
                ('IPBaseDatos', models.CharField(max_length=100)),
                ('comando_pendiente', models.CharField(blank=True, max_length=50, null=True)),
                ('ultima_conexion', models.DateTimeField(auto_now=True)),
                ('IDDispositivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tbltolva')),
            ],
        ),
    ]
