# Generated by Django 5.2.10 on 2026-02-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0011_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='namebase',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='control',
            name='passMysql',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='control',
            name='puerto',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='control',
            name='userMysql',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='control',
            name='IPBaseDatos',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='control',
            name='Token',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
