# Generated by Django 5.2.10 on 2026-02-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0012_control_namebase_control_passmysql_control_puerto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblConfiguracion',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Usuario', models.CharField(max_length=150, null=True)),
                ('BaseDeDatos', models.CharField(max_length=150, null=True)),
                ('FechaDescarga', models.DateTimeField(null=True)),
                ('FechaActualizacion', models.DateTimeField(max_length=150, null=True)),
                ('FolioSalMaquila', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
