# Generated by Django 5.2.10 on 2026-02-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0013_tblconfiguracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblServiciosWeb',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Servicio', models.BooleanField(null=True, verbose_name=True)),
                ('EstadoPago', models.BooleanField(null=True, verbose_name=True)),
                ('FechaVencimiento', models.DateField(null=True)),
                ('Notificacion', models.BooleanField(null=True, verbose_name=True)),
            ],
        ),
    ]
