# Generated by Django 4.1.13 on 2026-03-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0014_tblserviciosweb'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblconfiguracion',
            name='FolioRepServMov',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
