# Generated by Django 4.1.13 on 2026-03-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0015_tblconfiguracion_foliorepservmov'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblrepartidor',
            old_name='FechaServida',
            new_name='FechaServida1',
        ),
        migrations.AddField(
            model_name='tblconfiguracion',
            name='Porcentaje',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tblrepartidor',
            name='CantidadCena',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tblrepartidor',
            name='CantidadDesayuno',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tblrepartidor',
            name='FechaServida2',
            field=models.DateTimeField(max_length=150, null=True),
        ),
    ]
