# Generated by Django 4.1.13 on 2026-03-09 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0016_rename_fechaservida_tblrepartidor_fechaservida1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblrepartidor',
            old_name='CantidadCena',
            new_name='Cantidad1',
        ),
        migrations.RenameField(
            model_name='tblrepartidor',
            old_name='CantidadDesayuno',
            new_name='Cantidad2',
        ),
    ]
