# Generated by Django 4.1.13 on 2026-03-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0017_rename_cantidadcena_tblrepartidor_cantidad1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblconfiguracion',
            name='Porcentaje',
        ),
        migrations.AddField(
            model_name='tblrepartidor',
            name='Porcentaje',
            field=models.IntegerField(null=True),
        ),
    ]
