# Generated by Django 4.1.13 on 2026-03-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0018_remove_tblconfiguracion_porcentaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblrepartidor',
            name='SeSirve',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tblconfiguracion',
            name='BaseDeDatos',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tblconfiguracion',
            name='FechaActualizacion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tblconfiguracion',
            name='Usuario',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tblcorrales',
            name='Clave',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tblcorrales',
            name='Descripcion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tblcorrales',
            name='Fecha',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tblestatus',
            name='Descripcion',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tblmateriaprima',
            name='Descripcion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbloperadores',
            name='Descripcion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tblproductos',
            name='Descripcion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tblrepartidor',
            name='Fecha',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tblrepartidor',
            name='FechaServida1',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tblrepartidor',
            name='FechaServida2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tbltolva',
            name='Alias',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbltolva',
            name='Modelo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tblunidades',
            name='Abreviacion',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tblunidades',
            name='Descripcion',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
