# Generated by Django 4.1.13 on 2026-03-10 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0019_tblrepartidor_sesirve_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblrepartidor',
            old_name='Fecha',
            new_name='FechaSol',
        ),
        migrations.RemoveField(
            model_name='tblrepartidor',
            name='CantidadServida',
        ),
    ]
