# Generated by Django 4.1.13 on 2026-03-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0020_rename_fecha_tblrepartidor_fechasol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblconfiguracion',
            name='FolioOrdenServ',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
