# Generated by Django 4.1.13 on 2026-03-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0021_tblconfiguracion_folioordenserv'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblformulado',
            name='IDLoteMezclado',
            field=models.IntegerField(null=True),
        ),
    ]
