# Generated by Django 4.1.13 on 2026-03-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0022_tblformulado_idlotemezclado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblformulado',
            name='IDLoteMezclado',
        ),
        migrations.AddField(
            model_name='tblrepartidor',
            name='IDLoteMezclado',
            field=models.IntegerField(null=True),
        ),
    ]
