# Generated by Django 4.1.13 on 2026-04-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0023_remove_tblformulado_idlotemezclado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblrepartidor',
            name='CantidadAnimales',
            field=models.IntegerField(null=True),
        ),
    ]
